=== UPC/smeagol-perl/share/dtd/booking.dtd
<!ELEMENT booking (id?, description, ( ( from, to ) | (recurrence, duration) ), info?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT from (year, month, day, hour, minute, second)>
<!ELEMENT to (year, month, day, hour, minute, second)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT hour (#PCDATA)>
<!ELEMENT minute (#PCDATA)>
<!ELEMENT second (#PCDATA)>


<!-- Elements related to booking recurrence -->
<!ELEMENT recurrence (freq, interval?, dtstart?, dtend?, byminute?, byhour?, byday?, bymonthday?, bymonth?)>
<!ELEMENT freq (#PCDATA)> <!-- one of "minutely", "hourly", "daily", "weekly", "monthly", "yearly" -->
<!ELEMENT interval (#PCDATA)> <!-- The interval between recurrences. This is a multiplier for the value specified by "freq".  It defaults to 1 when <interval> element is not present. -->
<!ELEMENT duration (#PCDATA)> <!-- duration in minutes -->
<!ELEMENT dtstart (year, month, day, hour, minute, second)>
<!ELEMENT dtend (year, month, day, hour, minute, second)>
<!ELEMENT byminute (by+)> <!-- integers between 0 and 59 -->
<!ELEMENT byhour (by+)> <!-- integers between 0 and 23 -->
<!ELEMENT byday (by+)> <!-- "mo", "tu", "we", "th", "fr", "sa", "su". A prefix can be prepend to indicate i.e. "2fr" (second friday of month or year), "-1we" (last wednesday of month or year), etc -->
<!ELEMENT bymonthday (by+)> <!-- integers between 1 and 31, or negative integers between -31 and -1. "-1" is last day of month, etc -->
<!ELEMENT bymonth (by+)> <!-- integers between 1 and 12, or negative integers between -12 and -1 to indicate "last month of year", etc -->

<!ELEMENT by (#PCDATA)>

<!ELEMENT info ANY>
<!ATTLIST booking
    xmlns:xlink CDATA #IMPLIED
    xlink:href CDATA #IMPLIED
    xlink:type CDATA #IMPLIED>

=== UPC/smeagol-perl/doc/examples/booking-recurrence1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="application/xml" href="booking.xsl"?>
<!DOCTYPE booking SYSTEM "http://devel.cpl.upc.edu/recursos/export/HEAD/angel/xml/booking.dtd">

<!-- EXEMPLE: reserva per a les reunions setmanals de l'equip del projecte Sméagol -->
<!-- Reserva del recurs "30" (vegeu l'atribut xlink:href del node <booking>) cada dijous de 9:30 a 14:00 -->

<booking xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="/resource/30/booking/4">
    <id>4</id>
    <description>Reunió projecte Sméagol</description>
    <recurrence>
        <!-- repetir cada setmana -->
        <freq>weekly</freq>

        <!-- L'element <interval> seria redundant en aquest exemple,  -->
        <!-- ja que per defecte val 1 quan no està present.           -->
        <!-- Per reservar una setmana sí i una no, caldria interval 2 -->
        <interval>1</interval>

        <!-- duration: de 9:30 a 14:00 van 4 hores + 30 minuts = 270 minuts -->
        <duration>270</duration>

        <!-- Comencem a partir del dijous 9 de juliol de 2009 -->
        <dtstart>
            <year>2009</year><month>7</month><day>9</day><hour>9</hour><minute>30</minute><second>0</second>
        </dtstart>
        <!-- No hi ha element <dtend> (la reserva no acaba mai) -->

        <!-- El període reservat comença a les 9:30 -->
        <byhour>
            <by>9</by>
        </byhour>
        <byminute>
            <by>30</by>
        </byminute>

        <!-- Es reserven els dijous (thursday => th) -->
        <byday>
            <by>th</by>
        </byday>
    </recurrence>
    <info>
        <![CDATA[
        Reunió setmanal de l'equip Sméagol. Consulteu la llista de correu bla, bla, bla...
        L'element <info> pot contenir qualsevol tipus de dades 
        (per exemple, un altre document XML, una fotografia codificada 
        amb UUENCODE, etc). És tasca del client codificar, descodificar i interpretar
        el contingut d'aquest element, segons el format que s'hagi acordat prèviament.
        ]]>
    </info>
</booking>

=== UPC/smeagol-perl/doc/examples/booking-recurrence2.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="application/xml" href="booking.xsl"?>
<!DOCTYPE booking SYSTEM "http://devel.cpl.upc.edu/recursos/export/HEAD/angel/xml/booking.dtd">

<!-- EXEMPLE: reserva per a les reunions setmanals de l'equip del projecte Sméagol -->
<!-- Reserva del recurs "30" (vegeu l'atribut xlink:href del node <booking>) cada dijous de 9:30 a 14:00 -->

<booking xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="/resource/30/booking/4">
    <id>4</id>
    <description>Reunió projecte Sméagol</description>
    
    <!-- En el cas de reserves recurrents, els elements <from> i <to> que pengen      -->
    <!-- de l'arrel indiquen la DURACIÓ del període reservat                          -->
    <!-- En aquest cas, la duració seria de 4 hores i 30 minuts (de 9:30 a 14 hores), -->
    <!-- ja que el dia el mes i l'any són els mateixos en el from i en el <to>        -->
    <from>
        <year>2009</year><month>7</month><day>9</day><hour>9</hour><minute>30</minute><second>0</second>
    </from>
    <to>
        <year>2009</year><month>7</month><day>9</day><hour>14</hour><minute>0</minute><second>0</second>
    </to>
    <recurrence freq="weekly">
        <dtstart>
            <year>2009</year><month>7</month><day>9</day><hour>9</hour><minute>30</minute><second>0</second>
        </dtstart>
        <!-- No hi ha element <dtend> (la reserva no acaba mai) -->
        <byminute value="30"/>
        <byhour value="9"/>
        <byday value="th"/>
    </recurrence>
    <info>
        <![CDATA[
        Reunió setmanal de l'equip Sméagol. Consulteu la llista de correu bla, bla, bla...
        ]]>
    </info>
</booking>
